/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;

/**
 *
 * @author Aakash Gadhave
 */
public class Convicted_panel extends javax.swing.JPanel {

    /**
     * Creates new form Convicted_panel
     */
    
    DefaultListModel dm = new DefaultListModel();
    public Convicted_panel() {
        initComponents();
    }
    private int validate_all=0;
    private void add(String name){
         jList02.setModel(dm);
         dm.addElement(name);
         
     }
    
      
    private boolean check_regex(String regex,String inputString){
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(inputString);
        if (matcher.matches()) {
            return true;
        }
        else{
            return false;
        }
    }

    private void monthToYear()
    {
        int month;
        int remain=0;
        int year=0;
        if (monthsTextfield.getText().length()!=0) {
            
        
        month = Integer.parseInt(monthsTextfield.getText());
        if(month >= 12)
        {
            year = (month)/12;
          remain = (month)%12;
         System.out.println("\n years are="+year);
         System.out.println("\n months are="+remain);
         monthsTextfield.setText(Integer.toString(remain));
        }
        
        }
        
        if(yearsTextfield.getText().length()!=0){
            yearsTextfield.setText(Integer.toString(Integer.parseInt(yearsTextfield.getText())+year));
        }
        else{
            yearsTextfield.setText(Integer.toString(year));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        convictedBtnGrp = new javax.swing.ButtonGroup();
        convictedPanel = new javax.swing.JPanel();
        rigorousRdoBtn = new javax.swing.JRadioButton();
        simpleRdoBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        daysTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList02 = new javax.swing.JList<>();
        addConvicted = new javax.swing.JButton();
        deleteConvicted = new javax.swing.JButton();
        crimestxt1 = new javax.swing.JTextField();
        yearsTextfield = new javax.swing.JTextField();
        monthsTextfield = new javax.swing.JTextField();

        convictedPanel.setBackground(new java.awt.Color(255, 255, 255));
        convictedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rigorousRdoBtn.setBackground(new java.awt.Color(255, 255, 255));
        convictedBtnGrp.add(rigorousRdoBtn);
        rigorousRdoBtn.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        rigorousRdoBtn.setText("Rigorous");
        rigorousRdoBtn.setBorder(null);
        rigorousRdoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rigorousRdoBtnActionPerformed(evt);
            }
        });
        convictedPanel.add(rigorousRdoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        simpleRdoBtn.setBackground(new java.awt.Color(255, 255, 255));
        convictedBtnGrp.add(simpleRdoBtn);
        simpleRdoBtn.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        simpleRdoBtn.setText("Simple");
        simpleRdoBtn.setBorder(null);
        simpleRdoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpleRdoBtnMouseClicked(evt);
            }
        });
        simpleRdoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleRdoBtnActionPerformed(evt);
            }
        });
        convictedPanel.add(simpleRdoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Type");
        convictedPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 60, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Crimes");
        convictedPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Days");
        convictedPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Years");
        convictedPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Months");
        convictedPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Sentence Period");
        convictedPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 85, -1, -1));

        daysTextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        daysTextField.setText("0");
        daysTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        daysTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                daysTextFieldFocusLost(evt);
            }
        });
        daysTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysTextFieldActionPerformed(evt);
            }
        });
        convictedPanel.add(daysTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 30, -1));

        jList02.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jList02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList02MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList02);

        convictedPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 170, 80));

        addConvicted.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addConvicted.setText("Add");
        addConvicted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConvictedActionPerformed(evt);
            }
        });
        convictedPanel.add(addConvicted, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 80, -1));

        deleteConvicted.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteConvicted.setText("Delete");
        deleteConvicted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConvictedActionPerformed(evt);
            }
        });
        convictedPanel.add(deleteConvicted, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 80, -1));

        crimestxt1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        crimestxt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        crimestxt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                crimestxt1FocusLost(evt);
            }
        });
        crimestxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimestxt1ActionPerformed(evt);
            }
        });
        convictedPanel.add(crimestxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, 30));

        yearsTextfield.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        yearsTextfield.setText("0");
        yearsTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        yearsTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsTextfieldActionPerformed(evt);
            }
        });
        convictedPanel.add(yearsTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 30, -1));

        monthsTextfield.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        monthsTextfield.setText("0");
        monthsTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        monthsTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthsTextfieldFocusLost(evt);
            }
        });
        monthsTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthsTextfieldActionPerformed(evt);
            }
        });
        monthsTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monthsTextfieldKeyTyped(evt);
            }
        });
        convictedPanel.add(monthsTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(convictedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(convictedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteConvictedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConvictedActionPerformed
        // TODO add your handling code here:
        //Get Index,Update
        int index = jList02.getSelectedIndex();

        dm.removeElementAt(index);
        //Clear Text
        daysTextField.setText("");
    }//GEN-LAST:event_deleteConvictedActionPerformed

    private void addConvictedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConvictedActionPerformed
        // TODO add your handling code here:
        if(daysTextField.getText().length()!=0)
        {
           add(daysTextField.getText());
           daysTextField.setText("");
        }
    }//GEN-LAST:event_addConvictedActionPerformed

    private void jList02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList02MouseClicked
        // TODO add your handling code here:
        //String selected = jList02.getSelectedValue().toString();
        //crimestxt.setText(selected);
    }//GEN-LAST:event_jList02MouseClicked

    private void simpleRdoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleRdoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpleRdoBtnActionPerformed

    private void simpleRdoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpleRdoBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_simpleRdoBtnMouseClicked

    private void rigorousRdoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rigorousRdoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rigorousRdoBtnActionPerformed

    private void daysTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysTextFieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_daysTextFieldActionPerformed

    private void crimestxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimestxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crimestxt1ActionPerformed

    private void yearsTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsTextfieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_yearsTextfieldActionPerformed

    private void monthsTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthsTextfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_monthsTextfieldActionPerformed

    private void monthsTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthsTextfieldKeyTyped
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_monthsTextfieldKeyTyped

    private void monthsTextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthsTextfieldFocusLost
        // TODO add your handling code here:
         monthToYear();
    }//GEN-LAST:event_monthsTextfieldFocusLost

    private void daysTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daysTextFieldFocusLost
        // TODO add your handling code here:
         int days;
         int remain=0;
        int months=0;
         if (daysTextField.getText().length()!=0) {
            
        
        days = Integer.parseInt(daysTextField.getText());
        
             if (days > 365) {
                 days-=5;
                 
             }
        if(days > 30)
        {
            months = (days)/30;
          remain = (days)%30;
        
         System.out.println("\n months are="+months);
          System.out.println("\n days are="+remain);
        }
        }
         daysTextField.setText(Integer.toString(remain));
         
         if(monthsTextfield.getText().length()!=0){
            monthsTextfield.setText(Integer.toString(Integer.parseInt(monthsTextfield.getText())+months));
        }
        else{
            monthsTextfield.setText(Integer.toString(months));
        }
         
         
        monthToYear();
    }//GEN-LAST:event_daysTextFieldFocusLost

    private void crimestxt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_crimestxt1FocusLost
        // TODO add your handling code here:
        String regex = "[a-zA-Z]+";

        boolean isValid=check_regex(regex, crimestxt1.getText());

        if(isValid)
        {
             
            if(crimestxt1.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
            crimestxt1.setBackground(new Color(170, 253, 197));
        }
        else{
            if(crimestxt1.getBackground().getGreen()==253)
            {
                validate_all++;
            }
            crimestxt1.setBackground(new Color(255, 186, 187));
             
        }
    }//GEN-LAST:event_crimestxt1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConvicted;
    private javax.swing.ButtonGroup convictedBtnGrp;
    private javax.swing.JPanel convictedPanel;
    private javax.swing.JTextField crimestxt1;
    public javax.swing.JTextField daysTextField;
    private javax.swing.JButton deleteConvicted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList02;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField monthsTextfield;
    public javax.swing.JRadioButton rigorousRdoBtn;
    public javax.swing.JRadioButton simpleRdoBtn;
    public javax.swing.JTextField yearsTextfield;
    // End of variables declaration//GEN-END:variables
}
