/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import javax.swing.DefaultListModel;

/**
 *
 * @author Aakash Gadhave
 */
public class Under_trial_panel extends javax.swing.JPanel {

    /**
     * Creates new form Under_trial_panel
     */
    
      DefaultListModel dm = new DefaultListModel();
    public Under_trial_panel() {
        initComponents();
    }

    private void add(String name){
         jList02.setModel(dm);
         dm.addElement(name);
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        undertrialPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList02 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        Delete2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        casestxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Add1 = new javax.swing.JButton();
        Add2 = new javax.swing.JButton();

        undertrialPanel.setBackground(new java.awt.Color(255, 255, 255));
        undertrialPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(36, 47, 65));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Remarks");
        undertrialPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 90, 20));

        jList02.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jList02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList02MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList02);

        undertrialPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 170, 80));

        jList2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        undertrialPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 130, 70));

        Delete2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Delete2.setText("Delete");
        Delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete2ActionPerformed(evt);
            }
        });
        undertrialPanel.add(Delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 80, -1));

        jLabel17.setBackground(new java.awt.Color(36, 47, 65));
        jLabel17.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Cases");
        undertrialPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 20));

        casestxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        casestxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        casestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casestxtActionPerformed(evt);
            }
        });
        undertrialPanel.add(casestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 170, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        undertrialPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 240, 130));

        Add1.setBackground(new java.awt.Color(255, 255, 255));
        Add1.setText("Add");
        undertrialPanel.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 480, 60, -1));

        Add2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Add2.setText("Add");
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });
        undertrialPanel.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(undertrialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(undertrialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList02MouseClicked
        // TODO add your handling code here:
       // String selected = jList02.getSelectedValue().toString();
        //casestxt.setText(selected);
    }//GEN-LAST:event_jList02MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jList2MouseClicked

    private void Delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete2ActionPerformed
        // TODO add your handling code here:
        //Get Index,Update
        int index = jList02.getSelectedIndex();

        dm.removeElementAt(index);
        //Clear Text
        casestxt.setText("");
    }//GEN-LAST:event_Delete2ActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
        // TODO add your handling code here:
             if(casestxt.getText().length()!=0)
        {
           add(casestxt.getText());
           casestxt.setText("");
        }
    }//GEN-LAST:event_Add2ActionPerformed

    private void casestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casestxtActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_casestxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add2;
    private javax.swing.JButton Delete2;
    private javax.swing.JTextField casestxt;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JList<String> jList02;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel undertrialPanel;
    // End of variables declaration//GEN-END:variables
}
