/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import javax.swing.DefaultListModel;


/**
 *
 * @author Aakash Gadhave
 */
public class UnderTrial extends javax.swing.JFrame {

    /**
     * Creates new form UnderTrial
     */
    DefaultListModel dm = new DefaultListModel();
    public UnderTrial() {
        initComponents();
    }
    
    //Add To The List
     private void add(String name){
         jList02.setModel(dm);
         dm.addElement(name);
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        undertrialPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList02 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        Add = new javax.swing.JButton();
        Update2 = new javax.swing.JButton();
        Delete2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        nametxt2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Add1 = new javax.swing.JButton();
        Add2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        undertrialPanel.setBackground(new java.awt.Color(255, 255, 255));
        undertrialPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(36, 47, 65));
        jLabel16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Remarks");
        undertrialPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 90, 20));

        jList02.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jList02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList02MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList02);

        undertrialPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 130, 70));

        jList2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        undertrialPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 130, 70));

        Add.setBackground(new java.awt.Color(255, 255, 255));
        Add.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Add.setText("Submit");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        undertrialPanel.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 315, 90, 30));

        Update2.setBackground(new java.awt.Color(255, 255, 255));
        Update2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Update2.setText("Update");
        Update2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update2ActionPerformed(evt);
            }
        });
        undertrialPanel.add(Update2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        Delete2.setBackground(new java.awt.Color(255, 255, 255));
        Delete2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Delete2.setText("Delete");
        Delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete2ActionPerformed(evt);
            }
        });
        undertrialPanel.add(Delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel17.setBackground(new java.awt.Color(36, 47, 65));
        jLabel17.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Cases");
        undertrialPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 90, 20));

        nametxt2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nametxt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        undertrialPanel.add(nametxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        undertrialPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 110));

        Add1.setBackground(new java.awt.Color(255, 255, 255));
        Add1.setText("Add");
        undertrialPanel.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 480, 60, -1));

        Add2.setBackground(new java.awt.Color(255, 255, 255));
        Add2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Add2.setText("Add");
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });
        undertrialPanel.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 60, -1));

        getContentPane().add(undertrialPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList02MouseClicked
        // TODO add your handling code here:
        String selected = jList02.getSelectedValue().toString();
        nametxt2.setText(selected);
    }//GEN-LAST:event_jList02MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jList2MouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        add(nametxt2.getText());
        nametxt2.setText("");
    }//GEN-LAST:event_AddActionPerformed

    private void Update2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update2ActionPerformed
        // TODO add your handling code here:

        //Get Index,Update
        int index = jList02.getSelectedIndex();

        dm.setElementAt(nametxt2.getText(), index);

        //Clear Text
        nametxt2.setText("");
    }//GEN-LAST:event_Update2ActionPerformed

    private void Delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete2ActionPerformed
        // TODO add your handling code here:
        //Get Index,Update
        int index = jList02.getSelectedIndex();

        dm.removeElementAt(index);
        //Clear Text
        nametxt2.setText("");

    }//GEN-LAST:event_Delete2ActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
        // TODO add your handling code here:
         add(nametxt2.getText());
        nametxt2.setText("");
    }//GEN-LAST:event_Add2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnderTrial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnderTrial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnderTrial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnderTrial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnderTrial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add2;
    private javax.swing.JButton Delete2;
    private javax.swing.JButton Update2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JList<String> jList02;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nametxt2;
    private javax.swing.JPanel undertrialPanel;
    // End of variables declaration//GEN-END:variables
}
