/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

/**
 *
 * @author 702
 */
public class add_requirement_working_hrs_panel extends javax.swing.JPanel {

    /**
     * Creates new form add_requirement_working_hrs_panel
     */
    public add_requirement_working_hrs_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workhrs_start_time2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        workhrs_end_time2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(175, 30));
        setMinimumSize(new java.awt.Dimension(175, 30));
        setPreferredSize(new java.awt.Dimension(175, 30));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workhrs_start_time2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        workhrs_start_time2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workhrs_start_time2.setText("14:00");
        workhrs_start_time2.setOpaque(true);
        add(workhrs_start_time2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("to");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 20, 30));

        workhrs_end_time2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        workhrs_end_time2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workhrs_end_time2.setText("17:00");
        workhrs_end_time2.setOpaque(true);
        add(workhrs_end_time2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 70, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel workhrs_end_time2;
    public javax.swing.JLabel workhrs_start_time2;
    // End of variables declaration//GEN-END:variables
}
