/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import databaseConnectivity.MyPrisonConnection;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Clock;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
//import net.proteanit.sql.DbUtils;


//this is a git demo


/**
 *
 * @author Aakash Gadhave
 */
public class Allocate_Work_search extends javax.swing.JPanel {

    /**
     * Creates new form Allocate_Work_search
     */
     Connection con = null;
     private jailor_Dash jd;
     JPanel loadingPanel;
     private String c_id;
     private search_load_panel_allocate_work search;
     private jailor_dash_prisoner_schedule_load_panel schedule;
     //PreparedStatement pst2;
     //ResultSet rs2;
     //public String c_id;
     
     
    public Allocate_Work_search(JPanel ref) {
        initComponents();
        loadingPanel=ref;
        
       
        MyPrisonConnection o = new MyPrisonConnection();
        con = o.getMyConnection();
//        c_id = p_id;
       // fetch();
    }

       
  /*  public Allocate_Work_search(String c_id) {
        initComponents();
        
        
        this.c_id=c_id;
       
        MyPrisonConnection o = new MyPrisonConnection();
        con = o.getMyConnection();
        
        
       
    }*/
  //  public void fetch(){
      /*  
        String q = "SELECT c_id,p_firstname,p_midname,p_lastname FROM convicted_prisoner";
         try {
             pst2 = con.prepareStatement(q);
             rs2 = pst2.executeQuery();
             
             search_records_table.setModel(DbUtils.resultSetToTableModel(rs2));
         } catch (SQLException ex) {
             Logger.getLogger(Allocate_Work_search.class.getName()).log(Level.SEVERE, null, ex);
         }
        */
    //}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchtxtf = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loadin_panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 21)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 270, -1));

        searchtxtf.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        searchtxtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchtxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtfActionPerformed(evt);
            }
        });
        searchtxtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchtxtfKeyTyped(evt);
            }
        });
        jPanel1.add(searchtxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 260, 30));

        search_button.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(750, 450));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(750, 450));

        loadin_panel.setBackground(new java.awt.Color(255, 255, 255));
        loadin_panel.setLayout(new javax.swing.BoxLayout(loadin_panel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(loadin_panel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 750, 420));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1110, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void searchtxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxtfActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        
       if(searchtxtf.getText().equals(""))
       {
           JOptionPane.showMessageDialog(null, "Enter prisoner name");
           return;
       }
                 
                  
       String qString = "SELECT c_id,p_firstname,p_midname,p_lastname,p_occupation,p_qualification,c_type FROM convicted_prisoner WHERE p_firstname LIKE ? AND CURRENT_DATE()<releasedate(c_id)";
       
   
        PreparedStatement pst,pstmt;
        ResultSet rs,res;
         Allocate_work aw = new Allocate_work(c_id);
   //     PreparedStatement pst1;
         try {
             pst = con.prepareStatement(qString);
             pst.setString(1, searchtxtf.getText());
            
             
             
           rs = pst.executeQuery();
             
             
             
                 
             if(rs.next()){                
             String c_id  =  rs.getString("c_id");
             String first_name = rs.getString("p_firstname");
             String middle_name = rs.getString("p_midname");
              String last_name = rs.getString("p_lastname");
             String occupation =  rs.getString("p_occupation");
             String qualification = rs.getString("p_qualification");
             String type = rs.getString("c_type");
             
             String full_name = first_name+" "+middle_name+" "+last_name;
                     //loadingPanel = (JPanel)this.getParent();
                   
                 loadingPanel.removeAll();
                 
                  loadingPanel.add(aw, BorderLayout.CENTER);
                  loadingPanel.revalidate();
                  loadingPanel.repaint();
                  
             aw.fetch_id.setText(c_id);
             aw.fetch_name.setText(full_name);
             aw.fetch_type.setText(type);
             aw.fetch_occupation.setText(occupation);
             aw.fetch_qualification.setText(qualification);
                  
             
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Record not found.");
             }
             
      
         
        } catch (SQLException ex) {
            Logger.getLogger(Allocate_Work_search.class.getName()).log(Level.SEVERE, null, ex);
     }
         
       /*  String start_time,end_time,unit_name;
         String q = "SELECT h.unit_code,u.unit_name,s.head_id,s.s_starttime,s.s_sendtime FROM schedule s INNER JOIN head h ON s.head_id=h.head_id INNER JOIN unit u ON u.unit_code=h.unit_code WHERE c_id=?;";
     
         try {
             pstmt = con.prepareStatement(q);
             pstmt.setString(1, c_id);
             res = pstmt.executeQuery();
             
             aw.schedule_loadpanel.removeAll();
             while (res.next()) {     
                 
                 start_time = res.getString("s_starttime");
                 end_time = res.getString("s_sendtime");
                 unit_name = res.getString("unit_name");
                 
                 System.out.println(start_time);
                 
                 schedule = new jailor_dash_prisoner_schedule_load_panel(start_time, end_time, unit_name);
                 aw.schedule_loadpanel.add(schedule);
                 aw.schedule_loadpanel.revalidate();
                 aw.schedule_loadpanel.repaint();
                 schedule.fetch_schedule_start_time.setText(start_time);
                 schedule.fetch_schedule_end_time.setText(end_time);
                 schedule.fetch_untname_label.setText(unit_name);
             }
         } catch (SQLException ex) {
             Logger.getLogger(Allocate_Work_search.class.getName()).log(Level.SEVERE, null, ex);
         }*/ 
         
    }//GEN-LAST:event_search_buttonActionPerformed

    private void searchtxtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtfKeyReleased
        // TODO add your handling code here:
      //  String st = searchtxtf.getText().trim();
        
        //String query = "SELECT "
    }//GEN-LAST:event_searchtxtfKeyReleased
//OD113618036216704000
    private void searchtxtfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtfKeyTyped
        // TODO add your handling code here:
        String searchstr=searchtxtf.getText();
        
        if(evt.getKeyChar()==java.awt.event.KeyEvent.VK_BACK_SPACE)
        {
            System.out.println("Im in BACKSPACE");
            
        }
        else
        {
            searchstr=searchtxtf.getText()+evt.getKeyChar();
            
        }
        System.out.println(searchstr+" "+searchstr.length());
        
        if(searchstr.isEmpty())
        {
            System.out.println("in if....");
            loadin_panel.removeAll();
            loadin_panel.revalidate();
            loadin_panel.repaint();
        }
        else
        {
            System.out.println("in else.....");
        String query = "SELECT c_id,p_firstname,p_midname,p_lastname FROM convicted_prisoner WHERE p_firstname LIKE '"+searchstr+"%'";
        PreparedStatement pst;
        ResultSet rs;
        String pris,fir_name,mi_name,l_nm;
         try {
             pst = con.prepareStatement(query);
             // searchtxtf.getText()+"%");
             rs = pst.executeQuery();
             loadin_panel.removeAll();
             while(rs.next()){
                   
                   pris = rs.getString("c_id");
                   fir_name = rs.getString("p_firstname");
                   mi_name = rs.getString("p_midname");
                   l_nm = rs.getString("p_lastname");
                   
                   search = new search_load_panel_allocate_work(pris,loadingPanel);
                   
                   search.fetch_id_label.setText(pris);
                   search.fetch_name_label.setText(fir_name+" "+mi_name+" "+l_nm);
 
                   loadin_panel.add(search);
                   loadin_panel.revalidate();
                   loadin_panel.repaint();
               /*   prison_work = new prisoners_working_in_unit_panel();
                String pr_id = rs.getString("c_id");
                System.out.println(pr_id);
                String first_name = rs.getString("p_firstname");
                String mid_name = rs.getString("p_midname");
                String last_name = rs.getString("p_lastname");
                String fullname = (first_name+" "+mid_name+" "+last_name);
                String end_date1 = rs.getString("end_date");
                prison_work.fetch_id_label.setText(pr_id);
                prison_work.fetch_name_label.setText(fullname);
                prison_work.fetch_end_date_label.setText(end_date1);
               
                status_view.active_prisoner_panel.add(prison_work);
                status_view.active_prisoner_panel.revalidate();
                status_view.active_prisoner_panel.repaint();*/
             }
         } catch (SQLException ex) {
             Logger.getLogger(Allocate_Work_search.class.getName()).log(Level.SEVERE, null, ex);
         }
        }
    }//GEN-LAST:event_searchtxtfKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel loadin_panel;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField searchtxtf;
    // End of variables declaration//GEN-END:variables
}
