/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import databaseConnectivity.MyPrisonConnection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Aakash Gadhave
 */
public class head_dash extends javax.swing.JFrame {

    /**
     * 
     * Creates new form head_dash
     */
    String current_head_id;
    private add_Requirement add_req;
    
    Connection con=null;
    
    public head_dash(String logged_in_head_id) {
        initComponents();
        
           MyPrisonConnection o = new MyPrisonConnection();
                con = o.getMyConnection();
        current_head_id = logged_in_head_id;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        head_id_label.setText(current_head_id);
        
        String q = "SELECT h_firstname,h_lastname FROM head WHERE head_id=?";
        PreparedStatement pst5;
        try {
            pst5 = con.prepareStatement(q);
            pst5.setString(1, current_head_id);
            
            ResultSet rs5 = pst5.executeQuery();
            
            if(rs5.next())
            {
           String first_name =  rs5.getString("h_firstname");
            String last_name = rs5.getString("h_lastname");
            
            System.out.println(first_name);
            System.out.println(last_name);
            head_name_label.setText(first_name+" "+last_name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(head_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    
        
        
    }
    private add_Requirement aRequirement;
    private Mark_Attendance mark_Attendance;
    private requirement_panel req_panel;
    
    private final Color original = new Color(52, 58, 64);
    private final Color clicked  = new Color(23, 162, 184);
    private final Color focusColor = new Color(40, 122, 230);
    
    private void setAllBlack(){
        
    homeLabel.setBackground(original);
    schedulePrisonerLabel.setBackground(original);
    modifyPrisoner.setBackground(original);
    addRequirementsLabel.setBackground(original);
    modifyRequirementsLabel.setBackground(original);
    viewRequirementsLabel.setBackground(original);
    viewAttendanceLabel.setBackground(original);
    modifyAttendanceLabel.setBackground(original);
    emergencyLabel.setBackground(new Color(73, 78, 83));
        
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        optionsPanel = new javax.swing.JPanel();
        prisonerLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addRequirementsLabel = new javax.swing.JLabel();
        viewRequirementsLabel = new javax.swing.JLabel();
        modifyRequirementsLabel = new javax.swing.JLabel();
        requirementsMenuLabel = new javax.swing.JLabel();
        schedulePrisonerLabel = new javax.swing.JLabel();
        modifyPrisoner = new javax.swing.JLabel();
        attendanceMenuLabel = new javax.swing.JLabel();
        viewAttendanceLabel = new javax.swing.JLabel();
        modifyAttendanceLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        emergencyLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        head_id_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        head_name_label = new javax.swing.JLabel();
        loadingPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        mark_Attendance_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setLayout(new java.awt.BorderLayout());

        optionsPanel.setBackground(new java.awt.Color(52, 58, 64));
        optionsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prisonerLabel.setBackground(new java.awt.Color(73, 78, 83));
        prisonerLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        prisonerLabel.setForeground(new java.awt.Color(255, 255, 255));
        prisonerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prisonerLabel.setText("  Prisoner");
        prisonerLabel.setAlignmentX(1.0F);
        prisonerLabel.setOpaque(true);
        optionsPanel.add(prisonerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 123, 200, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        optionsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 364, -1, 25));

        addRequirementsLabel.setBackground(new java.awt.Color(52, 58, 64));
        addRequirementsLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        addRequirementsLabel.setForeground(new java.awt.Color(204, 204, 204));
        addRequirementsLabel.setText("  Add");
        addRequirementsLabel.setOpaque(true);
        addRequirementsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRequirementsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addRequirementsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addRequirementsLabelMouseExited(evt);
            }
        });
        optionsPanel.add(addRequirementsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 270, 176, 30));

        viewRequirementsLabel.setBackground(new java.awt.Color(52, 58, 64));
        viewRequirementsLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        viewRequirementsLabel.setForeground(new java.awt.Color(204, 204, 204));
        viewRequirementsLabel.setText("  View");
        viewRequirementsLabel.setOpaque(true);
        viewRequirementsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRequirementsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewRequirementsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewRequirementsLabelMouseExited(evt);
            }
        });
        optionsPanel.add(viewRequirementsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 300, 176, 30));

        modifyRequirementsLabel.setBackground(new java.awt.Color(52, 58, 64));
        modifyRequirementsLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        modifyRequirementsLabel.setForeground(new java.awt.Color(204, 204, 204));
        modifyRequirementsLabel.setText("  Modify");
        modifyRequirementsLabel.setOpaque(true);
        modifyRequirementsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyRequirementsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyRequirementsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyRequirementsLabelMouseExited(evt);
            }
        });
        optionsPanel.add(modifyRequirementsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 330, 176, 30));

        requirementsMenuLabel.setBackground(new java.awt.Color(73, 78, 83));
        requirementsMenuLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        requirementsMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        requirementsMenuLabel.setText("  Requirements");
        requirementsMenuLabel.setOpaque(true);
        optionsPanel.add(requirementsMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 40));

        schedulePrisonerLabel.setBackground(new java.awt.Color(52, 58, 64));
        schedulePrisonerLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        schedulePrisonerLabel.setForeground(new java.awt.Color(204, 204, 204));
        schedulePrisonerLabel.setText("  Schedule");
        schedulePrisonerLabel.setOpaque(true);
        schedulePrisonerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schedulePrisonerLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                schedulePrisonerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                schedulePrisonerLabelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                schedulePrisonerLabelMouseReleased(evt);
            }
        });
        optionsPanel.add(schedulePrisonerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 163, 176, 30));

        modifyPrisoner.setBackground(new java.awt.Color(52, 58, 64));
        modifyPrisoner.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        modifyPrisoner.setForeground(new java.awt.Color(204, 204, 204));
        modifyPrisoner.setText("  Modify ");
        modifyPrisoner.setOpaque(true);
        modifyPrisoner.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                modifyPrisonerAncestorRemoved(evt);
            }
        });
        modifyPrisoner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyPrisonerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyPrisonerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyPrisonerMouseExited(evt);
            }
        });
        optionsPanel.add(modifyPrisoner, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 193, 176, 30));

        attendanceMenuLabel.setBackground(new java.awt.Color(73, 78, 83));
        attendanceMenuLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        attendanceMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        attendanceMenuLabel.setText("  Attendance");
        attendanceMenuLabel.setOpaque(true);
        optionsPanel.add(attendanceMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 367, 200, 40));

        viewAttendanceLabel.setBackground(new java.awt.Color(52, 58, 64));
        viewAttendanceLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        viewAttendanceLabel.setForeground(new java.awt.Color(204, 204, 204));
        viewAttendanceLabel.setText("  View");
        viewAttendanceLabel.setOpaque(true);
        viewAttendanceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAttendanceLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAttendanceLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAttendanceLabelMouseExited(evt);
            }
        });
        optionsPanel.add(viewAttendanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 407, 176, 30));

        modifyAttendanceLabel.setBackground(new java.awt.Color(52, 58, 64));
        modifyAttendanceLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        modifyAttendanceLabel.setForeground(new java.awt.Color(204, 204, 204));
        modifyAttendanceLabel.setText("  Modify ");
        modifyAttendanceLabel.setOpaque(true);
        modifyAttendanceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyAttendanceLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyAttendanceLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyAttendanceLabelMouseExited(evt);
            }
        });
        optionsPanel.add(modifyAttendanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 437, 176, 30));

        homeLabel.setBackground(new java.awt.Color(52, 58, 64));
        homeLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setText("  Home");
        homeLabel.setOpaque(true);
        homeLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                homeLabelFocusLost(evt);
            }
        });
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLabelMouseExited(evt);
            }
        });
        optionsPanel.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 83, 200, 40));

        emergencyLabel.setBackground(new java.awt.Color(73, 78, 83));
        emergencyLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        emergencyLabel.setForeground(new java.awt.Color(255, 255, 255));
        emergencyLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emergencyLabel.setText("  Emergency");
        emergencyLabel.setAlignmentY(0.3F);
        emergencyLabel.setOpaque(true);
        emergencyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emergencyLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emergencyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emergencyLabelMouseExited(evt);
            }
        });
        optionsPanel.add(emergencyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 474, 200, 40));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view.png"))); // NOI18N
        optionsPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 407, -1, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tasks.png"))); // NOI18N
        optionsPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 367, -1, 40));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/siren.png"))); // NOI18N
        optionsPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 474, -1, 40));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        optionsPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 437, 20, 30));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        optionsPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 193, 20, 30));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calendar.png"))); // NOI18N
        optionsPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 163, 20, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        optionsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 30));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view.png"))); // NOI18N
        optionsPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 20, 30));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        optionsPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 20, 30));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        optionsPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file.png"))); // NOI18N
        optionsPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 40));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/prisoner.png"))); // NOI18N
        optionsPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, 40));

        backgroundPanel.add(optionsPanel, java.awt.BorderLayout.LINE_START);

        topPanel.setBackground(new java.awt.Color(52, 58, 64));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jLabel7.setToolTipText("Logout");
        topPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, 21));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logout");
        topPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1307, 39, -1, -1));

        jLabel4.setBackground(new java.awt.Color(73, 78, 83));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Head ID");
        jLabel4.setOpaque(true);
        topPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 120, 30));

        head_id_label.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        head_id_label.setForeground(new java.awt.Color(204, 204, 204));
        head_id_label.setText("H001");
        topPanel.add(head_id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 30));

        jLabel8.setBackground(new java.awt.Color(73, 78, 83));
        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Name");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        topPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 100, 30));

        head_name_label.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        head_name_label.setForeground(new java.awt.Color(204, 204, 204));
        head_name_label.setText("Abhishek Muddhebihal");
        topPanel.add(head_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, 30));

        backgroundPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        loadingPanel.setBackground(new java.awt.Color(255, 255, 255));
        loadingPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(40, 122, 230));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jButton1.setText("Submit Feedback");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 40));

        mark_Attendance_button.setBackground(new java.awt.Color(52, 58, 64));
        mark_Attendance_button.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        mark_Attendance_button.setText("Mark Attendance");
        mark_Attendance_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark_Attendance_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(mark_Attendance_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 40));

        loadingPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 58, 64));
        jLabel2.setText("Notifications");
        loadingPanel.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        backgroundPanel.add(loadingPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(backgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRequirementsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRequirementsLabelMouseClicked
        // TODO add your handling code here:
        setAllBlack();
        addRequirementsLabel.setBackground(clicked);
        
        loadingPanel.removeAll();
        aRequirement = new add_Requirement();
        loadingPanel.add(aRequirement, BorderLayout.CENTER);
        loadingPanel.revalidate();
        loadingPanel.repaint();
        
        Connection con = null;
        MyPrisonConnection o = new MyPrisonConnection();
        con = o.getMyConnection();
        
        //aRequirement.active_requirement_panel.removeAll();
       // req_panel = new requirement_panel();
       // aRequirement.active_requirement_panel.add(req_panel);
       // aRequirement.active_requirement_panel.add(new requirement_panel());
        
       // aRequirement.active_requirement_panel.add(new requirement_panel());
        
      
        
        PreparedStatement pst3,pst4;
          ResultSet rs,rs1;
        try {
            
            
           // String unit = "SELECT unit_name FROM unit WHERE unit_code=(SELECT unit_code FROM head WHERE head_id = ?)";
            //pst4 = con.prepareStatement(unit);
            //pst4.setString(1, current_head_id);
            //rs1 = pst4.executeQuery();
            
            
            //while (rs1.next()) {                
                //add_req = new add_Requirement();
              //  String st = rs1.getString("unit_name");
               // System.out.println(st);
                
                //add_req.unit_name_label.setText(st);
             // add_req.unit_name_label.revalidate();
              //add_req.unit_name_label.repaint();
              
              
            
            
              String s = "SELECT req_name,DATE_FORMAT(reqend(req_id),'%d/%m/%y') AS end_date,TIME_FORMAT(rstart_time,'%H:%i') AS rstart_time,TIME_FORMAT(rduration(req_id),'%H:%i') AS rend_time FROM requirements WHERE unit_code=(SELECT unit_code FROM head WHERE head_id=?)";
             pst3= con.prepareStatement(s);
           
             
             pst3.setString(1, current_head_id);
             
            rs = pst3.executeQuery();
            while (rs.next()) {            
            req_panel = new requirement_panel();
            req_panel.requirement_label_name.setText(rs.getString("req_name"));
            req_panel.end_date.setText(rs.getString("end_date"));
            req_panel.start_time.setText(rs.getString("rstart_time"));
            req_panel.end_time.setText(rs.getString("rend_time"));
            aRequirement.active_requirement_panel.add(req_panel);
            
          //  aRequirement.active_requirement_panel(req_panel.requirement_label_name.setText(rs.getString("req_name")));
            
            
            
            aRequirement.active_requirement_panel.revalidate();
            aRequirement.active_requirement_panel.repaint();
            
            
        }
        } catch (SQLException ex) {
            Logger.getLogger(head_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_addRequirementsLabelMouseClicked

    private void addRequirementsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRequirementsLabelMouseEntered
        // TODO add your handling code here:
        if (addRequirementsLabel.getBackground().getBlue()!=184 && addRequirementsLabel.getBackground().getRed()!=23 && addRequirementsLabel.getBackground().getGreen()!=162) {

            addRequirementsLabel.setBackground(focusColor);
        }
    }//GEN-LAST:event_addRequirementsLabelMouseEntered

    private void addRequirementsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRequirementsLabelMouseExited
        // TODO add your handling code here:
        if (addRequirementsLabel.getBackground().getBlue()!=184 && addRequirementsLabel.getBackground().getRed()!=23 && addRequirementsLabel.getBackground().getGreen()!=162) {

            addRequirementsLabel.setBackground(original);
        }
    }//GEN-LAST:event_addRequirementsLabelMouseExited

    private void viewRequirementsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRequirementsLabelMouseClicked
        // TODO add your handling code here:
        setAllBlack();
        viewRequirementsLabel.setBackground(clicked);
    }//GEN-LAST:event_viewRequirementsLabelMouseClicked

    private void viewRequirementsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRequirementsLabelMouseEntered
        // TODO add your handling code here:
        if (viewRequirementsLabel.getBackground().getBlue()!=184 && viewRequirementsLabel.getBackground().getRed()!=23 && viewRequirementsLabel.getBackground().getGreen()!=162) {

            viewRequirementsLabel.setBackground(focusColor);
        }
    }//GEN-LAST:event_viewRequirementsLabelMouseEntered

    private void viewRequirementsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRequirementsLabelMouseExited
        // TODO add your handling code here:
        if (viewRequirementsLabel.getBackground().getBlue()!=184 && viewRequirementsLabel.getBackground().getRed()!=23 && viewRequirementsLabel.getBackground().getGreen()!=162) {

            viewRequirementsLabel.setBackground(original);
        }
    }//GEN-LAST:event_viewRequirementsLabelMouseExited

    private void modifyRequirementsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyRequirementsLabelMouseClicked
        // TODO add your handling code here:
        setAllBlack();
        modifyRequirementsLabel.setBackground(clicked);
    }//GEN-LAST:event_modifyRequirementsLabelMouseClicked

    private void modifyRequirementsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyRequirementsLabelMouseEntered
        // TODO add your handling code here:
        if (modifyRequirementsLabel.getBackground().getBlue()!=184 && modifyRequirementsLabel.getBackground().getRed()!=23 && modifyRequirementsLabel.getBackground().getGreen()!=162) {

            modifyRequirementsLabel.setBackground(focusColor);
        }
    }//GEN-LAST:event_modifyRequirementsLabelMouseEntered

    private void modifyRequirementsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyRequirementsLabelMouseExited
        // TODO add your handling code here:
        if (modifyRequirementsLabel.getBackground().getBlue()!=184 && modifyRequirementsLabel.getBackground().getRed()!=23 && modifyRequirementsLabel.getBackground().getGreen()!=162) {

            modifyRequirementsLabel.setBackground(original);
        }
    }//GEN-LAST:event_modifyRequirementsLabelMouseExited

    private void schedulePrisonerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schedulePrisonerLabelMouseClicked
        // TODO add your handling code here:
        setAllBlack();
        schedulePrisonerLabel.setBackground(clicked);
        //  modifyPrisoner.setBackground(new Color(52, 58, 64));
        //viewPrisoner.setBackground(new Color(52, 58, 64));

     //   loadingPanel.removeAll();
       // loadingPanel.add(new registrationPanel(), BorderLayout.CENTER);
        //loadingPanel.revalidate();
        //loadingPanel.repaint();
        
         
        loadingPanel.removeAll();
        loadingPanel.add(new PrisonerSchedule(), BorderLayout.CENTER);
        loadingPanel.revalidate();
        loadingPanel.repaint();

    }//GEN-LAST:event_schedulePrisonerLabelMouseClicked

    private void schedulePrisonerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schedulePrisonerLabelMouseEntered
        // TODO add your handling code here:
        if (schedulePrisonerLabel.getBackground().getBlue()!=184 && schedulePrisonerLabel.getBackground().getRed()!=23 && schedulePrisonerLabel.getBackground().getGreen()!=162) {

            schedulePrisonerLabel.setBackground(focusColor);

        }

    }//GEN-LAST:event_schedulePrisonerLabelMouseEntered

    private void schedulePrisonerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schedulePrisonerLabelMouseExited
        // TODO add your handling code here:

        if (schedulePrisonerLabel.getBackground().getBlue()!=184 && schedulePrisonerLabel.getBackground().getRed()!=23 && schedulePrisonerLabel.getBackground().getGreen()!=162) {

            schedulePrisonerLabel.setBackground(original);

        }
    }//GEN-LAST:event_schedulePrisonerLabelMouseExited

    private void schedulePrisonerLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schedulePrisonerLabelMouseReleased
        // TODO add your handling code here:
        // addPrisoner1.setBackground(new Color(52,58,64));
        // addPrisoner1.repaint();
    }//GEN-LAST:event_schedulePrisonerLabelMouseReleased

    private void modifyPrisonerAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_modifyPrisonerAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyPrisonerAncestorRemoved

    private void modifyPrisonerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyPrisonerMouseClicked
        // TODO add your handling code here:
        setAllBlack();
        modifyPrisoner.setBackground(clicked);

    }//GEN-LAST:event_modifyPrisonerMouseClicked

    private void modifyPrisonerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyPrisonerMouseEntered
        // TODO add your handling code here:
        if (modifyPrisoner.getBackground().getBlue()!=184 && modifyPrisoner.getBackground().getRed()!=23 && modifyPrisoner.getBackground().getGreen()!=162) {

            modifyPrisoner.setBackground(focusColor);

        }

    }//GEN-LAST:event_modifyPrisonerMouseEntered

    private void modifyPrisonerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyPrisonerMouseExited
        // TODO add your handling code here:
        if (modifyPrisoner.getBackground().getBlue()!=184 && modifyPrisoner.getBackground().getRed()!=23 && modifyPrisoner.getBackground().getGreen()!=162) {

            modifyPrisoner.setBackground(original);

        }
    }//GEN-LAST:event_modifyPrisonerMouseExited

    private void viewAttendanceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAttendanceLabelMouseClicked
        // TODO add your handling code here:
        setAllBlack();
        viewAttendanceLabel.setBackground(clicked);
    }//GEN-LAST:event_viewAttendanceLabelMouseClicked

    private void viewAttendanceLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAttendanceLabelMouseEntered
        // TODO add your handling code here:
        if (viewAttendanceLabel.getBackground().getBlue()!=184 && viewAttendanceLabel.getBackground().getRed()!=23 && viewAttendanceLabel.getBackground().getGreen()!=162) {

            viewAttendanceLabel.setBackground(focusColor);
        }
    }//GEN-LAST:event_viewAttendanceLabelMouseEntered

    private void viewAttendanceLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAttendanceLabelMouseExited
        // TODO add your handling code here:
        if (viewAttendanceLabel.getBackground().getBlue()!=184 && viewAttendanceLabel.getBackground().getRed()!=23 && viewAttendanceLabel.getBackground().getGreen()!=162) {

            viewAttendanceLabel.setBackground(original);
        }
    }//GEN-LAST:event_viewAttendanceLabelMouseExited

    private void modifyAttendanceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyAttendanceLabelMouseClicked
        // TODO add your handling code here:
        setAllBlack();
        modifyAttendanceLabel.setBackground(clicked);
    }//GEN-LAST:event_modifyAttendanceLabelMouseClicked

    private void modifyAttendanceLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyAttendanceLabelMouseEntered
        // TODO add your handling code here:
        if (modifyAttendanceLabel.getBackground().getBlue()!=184 && modifyAttendanceLabel.getBackground().getRed()!=23 && modifyAttendanceLabel.getBackground().getGreen()!=162) {

            modifyAttendanceLabel.setBackground(focusColor);
        }
    }//GEN-LAST:event_modifyAttendanceLabelMouseEntered

    private void modifyAttendanceLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyAttendanceLabelMouseExited
        // TODO add your handling code here:
        if (modifyAttendanceLabel.getBackground().getBlue()!=184 && modifyAttendanceLabel.getBackground().getRed()!=23 && modifyAttendanceLabel.getBackground().getGreen()!=162) {

            modifyAttendanceLabel.setBackground(original);
        }
    }//GEN-LAST:event_modifyAttendanceLabelMouseExited

    private void homeLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeLabelFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_homeLabelFocusGained

    private void homeLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeLabelFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_homeLabelFocusLost

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        // TODO add your handling code here:
        setAllBlack();
        homeLabel.setBackground(clicked);

    }//GEN-LAST:event_homeLabelMouseClicked

    private void homeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseEntered
        // TODO add your handling code here:
        if (homeLabel.getBackground().getBlue()!=184 && homeLabel.getBackground().getRed()!=23 && homeLabel.getBackground().getGreen()!=162) {

            homeLabel.setBackground(focusColor);

        }

    }//GEN-LAST:event_homeLabelMouseEntered

    private void homeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseExited
        // TODO add your handling code here:

        if (homeLabel.getBackground().getBlue()!=184 && homeLabel.getBackground().getRed()!=23 && homeLabel.getBackground().getGreen()!=162) {

            homeLabel.setBackground(original);

        }

    }//GEN-LAST:event_homeLabelMouseExited

    private void emergencyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emergencyLabelMouseClicked
        // TODO add your handling code here:
        setAllBlack();
        emergencyLabel.setBackground(clicked);

    }//GEN-LAST:event_emergencyLabelMouseClicked

    private void emergencyLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emergencyLabelMouseEntered
        // TODO add your handling code here:
        if (emergencyLabel.getBackground().getBlue()!=184 && emergencyLabel.getBackground().getRed()!=23 && emergencyLabel.getBackground().getGreen()!=162) {

            emergencyLabel.setBackground(focusColor);
        }
    }//GEN-LAST:event_emergencyLabelMouseEntered

    private void emergencyLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emergencyLabelMouseExited
        // TODO add your handling code here:

        if (emergencyLabel.getBackground().getBlue()!=184 && emergencyLabel.getBackground().getRed()!=23 && emergencyLabel.getBackground().getGreen()!=162) {

            emergencyLabel.setBackground(original);
        }
    }//GEN-LAST:event_emergencyLabelMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mark_Attendance_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark_Attendance_buttonActionPerformed
        // TODO add your handling code here:
        loadingPanel.removeAll();
        mark_Attendance = new Mark_Attendance();
        loadingPanel.add(mark_Attendance , BorderLayout.CENTER);
        loadingPanel.revalidate();
        loadingPanel.repaint();

    }//GEN-LAST:event_mark_Attendance_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(head_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(head_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(head_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(head_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new head_dash("H01").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addRequirementsLabel;
    private javax.swing.JLabel attendanceMenuLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel emergencyLabel;
    private javax.swing.JLabel head_id_label;
    private javax.swing.JLabel head_name_label;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel loadingPanel;
    private javax.swing.JButton mark_Attendance_button;
    private javax.swing.JLabel modifyAttendanceLabel;
    private javax.swing.JLabel modifyPrisoner;
    private javax.swing.JLabel modifyRequirementsLabel;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JLabel prisonerLabel;
    private javax.swing.JLabel requirementsMenuLabel;
    private javax.swing.JLabel schedulePrisonerLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel viewAttendanceLabel;
    private javax.swing.JLabel viewRequirementsLabel;
    // End of variables declaration//GEN-END:variables
}
