/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

/**
 *
 * @author 702
 */
public class head_view_reports extends javax.swing.JPanel {

    /**
     * Creates new form head_view_reports
     */
    public head_view_reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        annual_report_label = new javax.swing.JLabel();
        fetch_unit_name_label1 = new javax.swing.JLabel();
        fetch_year = new javax.swing.JLabel();
        annual_report_label1 = new javax.swing.JLabel();
        annual_report_label3 = new javax.swing.JLabel();
        fetch_report_prisoners_employed1 = new javax.swing.JLabel();
        fetch_report_requirements_served1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(650, 310));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        annual_report_label.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        annual_report_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        annual_report_label.setText("Requirements Served");
        jPanel1.add(annual_report_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 220, 30));

        fetch_unit_name_label1.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        fetch_unit_name_label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_unit_name_label1.setText("Carpentry");
        jPanel1.add(fetch_unit_name_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, 30));

        fetch_year.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        fetch_year.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_year.setText("2016");
        jPanel1.add(fetch_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, 30));

        annual_report_label1.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        annual_report_label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        annual_report_label1.setText(" Unit Report");
        jPanel1.add(annual_report_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, 30));

        annual_report_label3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        annual_report_label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        annual_report_label3.setText("Prisoners Employed");
        jPanel1.add(annual_report_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 200, 30));

        fetch_report_prisoners_employed1.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        fetch_report_prisoners_employed1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_report_prisoners_employed1.setText("60");
        jPanel1.add(fetch_report_prisoners_employed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, 30));

        fetch_report_requirements_served1.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        fetch_report_requirements_served1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_report_requirements_served1.setText("20");
        jPanel1.add(fetch_report_requirements_served1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 400));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel annual_report_label;
    private javax.swing.JLabel annual_report_label1;
    private javax.swing.JLabel annual_report_label3;
    private javax.swing.JLabel fetch_report_prisoners_employed1;
    private javax.swing.JLabel fetch_report_requirements_served1;
    private javax.swing.JLabel fetch_unit_name_label1;
    public javax.swing.JLabel fetch_year;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
