/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import javax.swing.JPanel;

/**
 *
 * @author 702
 */
public class jailor_view_prisoner_history extends javax.swing.JPanel {

    /**
     * Creates new form jailor_view_prisoner_history
     */
    
    private know_more_panel know;
    JPanel view;
   
    public jailor_view_prisoner_history(JPanel ref) {
        initComponents();
        view = ref;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        fetch_no_of_times_worked_label1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fetch_unit_name_label1 = new javax.swing.JLabel();
        know_more_button1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        conduct_load_panel1 = new javax.swing.JPanel();
        performance_load_panel1 = new javax.swing.JPanel();
        attendance_load_panel1 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("No Of Times Worked");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, -1));

        fetch_no_of_times_worked_label1.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        fetch_no_of_times_worked_label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_no_of_times_worked_label1.setText("3");
        jPanel3.add(fetch_no_of_times_worked_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Conduct");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        fetch_unit_name_label1.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        fetch_unit_name_label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_unit_name_label1.setText("Carpentry");
        jPanel3.add(fetch_unit_name_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        know_more_button1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        know_more_button1.setText("Know More ->");
        know_more_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                know_more_button1ActionPerformed(evt);
            }
        });
        jPanel3.add(know_more_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Unit");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, -1));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Performance");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Attendance");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        conduct_load_panel1.setBackground(new java.awt.Color(255, 255, 255));
        conduct_load_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(conduct_load_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 120, 100));

        performance_load_panel1.setBackground(new java.awt.Color(255, 255, 255));
        performance_load_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(performance_load_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 120, 100));

        attendance_load_panel1.setBackground(new java.awt.Color(255, 255, 255));
        attendance_load_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(attendance_load_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 120, 100));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void know_more_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_know_more_button1ActionPerformed
       // TODO add your handling code here:
       know = new know_more_panel();
       view.removeAll();
       view.add(know);
       view.revalidate();
       view.repaint();    
    }//GEN-LAST:event_know_more_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attendance_load_panel1;
    private javax.swing.JPanel conduct_load_panel1;
    private javax.swing.JLabel fetch_no_of_times_worked_label1;
    private javax.swing.JLabel fetch_unit_name_label1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JButton know_more_button1;
    private javax.swing.JPanel performance_load_panel1;
    // End of variables declaration//GEN-END:variables
}
