/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import databaseConnectivity.MyPrisonConnection;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author 702
 */
public class jailor_notification_loadpanel extends javax.swing.JPanel {

    /**
     * Creates new form jailor_notification_loadpanel
     */
    String description,title;
    JPanel loadingPanel;
    Connection con;
    private Allocate_work allocate;
    public jailor_notification_loadpanel(String desc,JPanel ref,String ti) {
        initComponents();
         MyPrisonConnection o = new MyPrisonConnection();
                con = o.getMyConnection();
        description = desc;
        loadingPanel = ref;
        title = ti;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fetch_title_label = new javax.swing.JLabel();
        fetch_description_label = new javax.swing.JLabel();
        fetch_receive_label = new javax.swing.JLabel();
        view_btn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(880, 31));
        jPanel1.setMinimumSize(new java.awt.Dimension(880, 31));
        jPanel1.setPreferredSize(new java.awt.Dimension(801, 31));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fetch_title_label.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        fetch_title_label.setText("Title");
        jPanel1.add(fetch_title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        fetch_description_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fetch_description_label.setText("Description");
        jPanel1.add(fetch_description_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 6, -1, -1));

        fetch_receive_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fetch_receive_label.setText("Receive");
        jPanel1.add(fetch_receive_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 6, -1, -1));

        view_btn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        view_btn.setText("View");
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });
        jPanel1.add(view_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 6, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        // TODO add your handling code here:
             if(!title.equals("Allocate work to rigorous prisoner")){
             } else {
                 allocate = new Allocate_work();
                 loadingPanel.removeAll();
                 loadingPanel.add(allocate, BorderLayout.CENTER);
                 loadingPanel.revalidate();
                 loadingPanel.repaint();
                 PreparedStatement pst,pstm;
                 ResultSet res,resu;
                 String qu = "SELECT p_firstname,p_midname,p_lastname,c_type,p_occupation,p_qualification FROM convicted_prisoner WHERE c_id=?";
                 String f_nm,m_nm,l_nm,full_nm,type,occupation,qualification;
                 try {
                     pst = con.prepareStatement(qu);
                     pst.setString(1, description);
                     res = pst.executeQuery();
                     
                     while(res.next()){
                         f_nm = res.getString("p_firstname");
                         m_nm = res.getString("p_midname");
                         l_nm = res.getString("p_lastname");
                         full_nm = (f_nm+" "+" "+m_nm+" "+l_nm);
                         type = res.getString("c_type");
                         occupation = res.getString("p_occupation");
                         qualification = res.getString("p_qualification");
                         
                         allocate.fetch_id.setText(description);
                         allocate.fetch_name.setText(full_nm);
                         allocate.fetch_type.setText(type);
                         allocate.fetch_occupation.setText(occupation);
                         allocate.fetch_qualification.setText(qualification);
                     }
                 } catch (SQLException ex) {
                     Logger.getLogger(head_notification_loadpanel.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 String qw = "CALL rigorous_suggestion(?)";
                 try {
                     pstm = con.prepareStatement(qw);
                     pstm.setString(1, description);
                     resu = pstm.executeQuery();
                     
                     int suggest=0;
                     
                     if(!resu.next())
                     {
                         return;
                     }
                     suggest  =  resu.getInt("suggestions");
                     String unitname = resu.getString("unit_name");
                     allocate.suggestion1.setText(unitname);
                     allocate.initProgress(allocate.progress_panel,suggest);
                     
                     
                     
                     if(!resu.next())
                     {
                         return;
                     }
                     suggest  =  resu.getInt("suggestions");
                     unitname = resu.getString("unit_name");
                     allocate.suggestion2.setText(unitname);
                     allocate.initProgress(allocate.progress_panel1, suggest);
                     
                     if(!resu.next())
                     {
                         return;
                     }
                     suggest  =  resu.getInt("suggestions");
                     unitname = resu.getString("unit_name");
                     allocate.suggestion3.setText(unitname);
                     allocate.initProgress(allocate.progress_panel2, suggest);
                     
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(head_notification_loadpanel.class.getName()).log(Level.SEVERE, null, ex);
                 }
        }

    }//GEN-LAST:event_view_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel fetch_description_label;
    public javax.swing.JLabel fetch_receive_label;
    public javax.swing.JLabel fetch_title_label;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables
}
