/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

/**
 *
 * @author 702
 */
public class jailor_dash_prisoner_schedule_load_panel extends javax.swing.JPanel {

    /**
     * Creates new form jailor_dash_prisoner_schedule_load_panel
     */
    String start_time,end_time,unit_name;
    public jailor_dash_prisoner_schedule_load_panel(String s_time,String e_time,String u_name) {
        initComponents();
        start_time = s_time;
        end_time = e_time;
        unit_name = u_name;
        
       /* fetch_schedule_start_time.setText(start_time);
        fetch_schedule_end_time.setText(end_time);
        fetch_untname_label.setText(unit_name);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        fetch_schedule_start_time = new javax.swing.JLabel();
        fetch_schedule_end_time = new javax.swing.JLabel();
        fetch_untname_label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(370, 40));
        setMinimumSize(new java.awt.Dimension(370, 40));
        setPreferredSize(new java.awt.Dimension(370, 40));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setMaximumSize(new java.awt.Dimension(370, 40));
        jPanel6.setMinimumSize(new java.awt.Dimension(370, 40));
        jPanel6.setPreferredSize(new java.awt.Dimension(370, 40));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel18.setText("to");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        fetch_schedule_start_time.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        fetch_schedule_start_time.setText("16:00");
        jPanel6.add(fetch_schedule_start_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fetch_schedule_end_time.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        fetch_schedule_end_time.setText("17:00");
        jPanel6.add(fetch_schedule_end_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        fetch_untname_label.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        fetch_untname_label.setText("Cooking");
        jPanel6.add(fetch_untname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 40));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel fetch_schedule_end_time;
    public javax.swing.JLabel fetch_schedule_start_time;
    public javax.swing.JLabel fetch_untname_label;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
