/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import databaseConnectivity.MyPrisonConnection;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author 702
 */
public class jailor_view_prisoner_history extends javax.swing.JPanel {

    /**
     * Creates new form jailor_view_prisoner_history
     */
    JPanel ref;
    String p_id;
    private know_more_panel know;
    private jailor_view_prison_history view_history;
    Connection con;
    public jailor_view_prisoner_history(JPanel panel,String c_id) {
        initComponents();
         MyPrisonConnection o = new MyPrisonConnection();
             con = o.getMyConnection();
        ref = panel;
        p_id = c_id;
        
    }
    
     public void initProgress(javax.swing.JPanel objPanel,int max){
    
        
        ProgressPanel jpProgress = new ProgressPanel();
        objPanel.removeAll();
        objPanel.add(jpProgress,BorderLayout.CENTER);
        objPanel.revalidate();
        objPanel.repaint();
       drawProgress(jpProgress,max);
    }
   public void drawProgress(ProgressPanel objPanel ,int max){
     
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= max; i++) {
                    try {
                        objPanel.updateProgress(i);
                        objPanel.repaint();
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        System.out.println("Exception");
                    }
                    // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            }

        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        fetch_no_of_times_worked_label4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        fetch_unit_name_label4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        conduct_load_panel1 = new javax.swing.JPanel();
        performance_load_panel1 = new javax.swing.JPanel();
        attendance_load_panel1 = new javax.swing.JPanel();
        know_more_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("No Of Times Worked");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, -1));

        fetch_no_of_times_worked_label4.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        fetch_no_of_times_worked_label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_no_of_times_worked_label4.setText("3");
        jPanel6.add(fetch_no_of_times_worked_label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Conduct");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        fetch_unit_name_label4.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        fetch_unit_name_label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_unit_name_label4.setText("Carpentry");
        jPanel6.add(fetch_unit_name_label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Unit");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, -1));

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Performance");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 10, -1, -1));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Attendance");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 10, -1, -1));

        conduct_load_panel1.setBackground(new java.awt.Color(255, 255, 255));
        conduct_load_panel1.setLayout(new java.awt.BorderLayout());
        jPanel6.add(conduct_load_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 120, 100));

        performance_load_panel1.setBackground(new java.awt.Color(255, 255, 255));
        performance_load_panel1.setLayout(new java.awt.BorderLayout());
        jPanel6.add(performance_load_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 120, 100));

        attendance_load_panel1.setBackground(new java.awt.Color(255, 255, 255));
        attendance_load_panel1.setLayout(new java.awt.BorderLayout());
        jPanel6.add(attendance_load_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 120, 100));

        know_more_button.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        know_more_button.setText("Know More ->");
        know_more_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                know_more_buttonActionPerformed(evt);
            }
        });
        jPanel6.add(know_more_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 150, 30));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
        //this.setBackground(new Color(240, 240, 240));

    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
        //this.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel6MouseExited

    private void know_more_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_know_more_buttonActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst;
        ResultSet rs;
   
        String query = "SELECT c_id,sdate,no_of_days FROM feedback WHERE c_id=? AND head_id= (SELECT head_id FROM head WHERE unit_code = (SELECT unit_code FROM unit WHERE unit_name LIKE ?));";
        try {
              String u_name = fetch_unit_name_label4.getText();
           
            pst = con.prepareStatement(query);
            pst.setString(1, p_id);
            pst.setString(2, u_name);
            rs = pst.executeQuery();
            
           
            ref.removeAll();
            while (rs.next()) {
                 String from_date = rs.getString("sdate");
            int no_of_days = rs.getInt("no_of_days");
                System.out.println(from_date);
                System.out.println(no_of_days);
              know = new know_more_panel(u_name,from_date,no_of_days);
              
              
              ref.add(know);
              
                
            }
            ref.revalidate();
              ref.repaint();

        } catch (SQLException ex) {
            Logger.getLogger(jailor_view_prisoner_history.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_know_more_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel attendance_load_panel1;
    public javax.swing.JPanel conduct_load_panel1;
    public javax.swing.JLabel fetch_no_of_times_worked_label4;
    public javax.swing.JLabel fetch_unit_name_label4;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton know_more_button;
    public javax.swing.JPanel performance_load_panel1;
    // End of variables declaration//GEN-END:variables
}
