/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

/**
 *
 * @author Aakash Gadhave
 */
public class Mark_Attendance extends javax.swing.JPanel {

    /**
     * Creates new form Mark_Attendance
     */
    public Mark_Attendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attendance_Panel_left = new javax.swing.JPanel();
        mark_Label = new javax.swing.JLabel();
        C001_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        C001_panel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        C001_panel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        C001_panel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        C001_panel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        C001_panel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        C001_panel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        C001_panel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        C001_panel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        C001_panel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        C001_panel10 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        C001_panel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        C001_panel12 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        C001_panel13 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jCheckBox14 = new javax.swing.JCheckBox();
        C001_panel14 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jCheckBox15 = new javax.swing.JCheckBox();
        C001_panel15 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jCheckBox16 = new javax.swing.JCheckBox();
        C001_panel16 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jCheckBox17 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date_Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        attendance_Panel_left1 = new javax.swing.JPanel();
        attendance_Panel_left2 = new javax.swing.JPanel();
        mark_Label1 = new javax.swing.JLabel();
        C001_panel17 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jCheckBox18 = new javax.swing.JCheckBox();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        C001_panel18 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jCheckBox19 = new javax.swing.JCheckBox();
        C001_panel19 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jCheckBox20 = new javax.swing.JCheckBox();
        C001_panel20 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jCheckBox21 = new javax.swing.JCheckBox();
        C001_panel21 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jCheckBox22 = new javax.swing.JCheckBox();
        C001_panel22 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jCheckBox23 = new javax.swing.JCheckBox();
        C001_panel23 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jCheckBox24 = new javax.swing.JCheckBox();
        C001_panel24 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jCheckBox25 = new javax.swing.JCheckBox();
        C001_panel25 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jCheckBox26 = new javax.swing.JCheckBox();
        C001_panel26 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jCheckBox27 = new javax.swing.JCheckBox();
        C001_panel27 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jCheckBox28 = new javax.swing.JCheckBox();
        C001_panel28 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jCheckBox29 = new javax.swing.JCheckBox();
        C001_panel29 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jCheckBox30 = new javax.swing.JCheckBox();
        C001_panel30 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jCheckBox31 = new javax.swing.JCheckBox();
        C001_panel31 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jCheckBox32 = new javax.swing.JCheckBox();
        C001_panel32 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jCheckBox33 = new javax.swing.JCheckBox();
        C001_panel33 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jCheckBox34 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendance_Panel_left.setBackground(new java.awt.Color(255, 255, 255));
        attendance_Panel_left.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        attendance_Panel_left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mark_Label.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        mark_Label.setText("Present");
        attendance_Panel_left.add(mark_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 80, -1));

        C001_panel.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("C017");
        C001_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Akash J. Gadhave");
        C001_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 518, 572, 30));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel9.setText("ID");
        attendance_Panel_left.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel11.setText("Name");
        attendance_Panel_left.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 60, -1));

        C001_panel1.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("C001");
        C001_panel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Mayuresh  N.  Joshi");
        C001_panel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 38, 572, 30));

        C001_panel2.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("C002");
        C001_panel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Gaurav A. Deshpande");
        C001_panel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 68, 572, 30));

        C001_panel3.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("C003");
        C001_panel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Abhishek S. Kondekar");
        C001_panel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel3.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 98, 572, 30));

        C001_panel4.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("C004");
        C001_panel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Akash S. Madhavai");
        C001_panel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel4.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 128, 572, 30));

        C001_panel5.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("C005");
        C001_panel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Abhijeet J. Petkar");
        C001_panel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel5.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 158, 572, 30));

        C001_panel6.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("C006");
        C001_panel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Akash J. Gadhave");
        C001_panel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel6.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 188, 572, 30));

        C001_panel7.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("C007");
        C001_panel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Akash J. Gadhave");
        C001_panel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox8.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel7.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 218, 572, 30));

        C001_panel8.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("C008");
        C001_panel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Akash J. Gadhave");
        C001_panel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox9.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel8.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 248, 572, 30));

        C001_panel9.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("C009");
        C001_panel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Akash J. Gadhave");
        C001_panel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox10.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox10.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel9.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 278, 572, 30));

        C001_panel10.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("C010");
        C001_panel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Akash J. Gadhave");
        C001_panel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox11.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel10.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 308, 572, 30));

        C001_panel11.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("C011");
        C001_panel11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Akash J. Gadhave");
        C001_panel11.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox12.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox12.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel11.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 338, 572, 30));

        C001_panel12.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("C012");
        C001_panel12.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Akash J. Gadhave");
        C001_panel12.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox13.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox13.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel12.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 368, 572, 30));

        C001_panel13.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("C013");
        C001_panel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Akash J. Gadhave");
        C001_panel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox14.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox14.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel13.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 398, 572, 30));

        C001_panel14.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("C014");
        C001_panel14.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Akash J. Gadhave");
        C001_panel14.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox15.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox15.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel14.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 428, 572, 30));

        C001_panel15.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("C015");
        C001_panel15.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel41.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Akash J. Gadhave");
        C001_panel15.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox16.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox16.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel15.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 458, 572, 30));

        C001_panel16.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("C016");
        C001_panel16.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel43.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Akash J. Gadhave");
        C001_panel16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox17.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox17.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel16.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left.add(C001_panel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 488, 572, 30));

        add(attendance_Panel_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 575, 560));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel1.setText("28-09-2018");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 40));

        date_Label.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        date_Label.setText("Date");
        jPanel2.add(date_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel3.setText("Time");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel4.setText("18:30");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 40));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel5.setText("Unit");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Manufacturing");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 280, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 40));

        attendance_Panel_left1.setBackground(new java.awt.Color(255, 255, 255));
        attendance_Panel_left1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        attendance_Panel_left1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendance_Panel_left2.setBackground(new java.awt.Color(255, 255, 255));
        attendance_Panel_left2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        attendance_Panel_left2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mark_Label1.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        mark_Label1.setText("Present");
        attendance_Panel_left2.add(mark_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 80, -1));

        C001_panel17.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("C034");
        C001_panel17.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel45.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Akash J. Gadhave");
        C001_panel17.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox18.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox18.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel17.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 518, 572, 30));

        jLabel46.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel46.setText("ID");
        attendance_Panel_left2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, -1));

        jLabel47.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel47.setText("Name");
        attendance_Panel_left2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 60, -1));

        C001_panel18.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("C018");
        C001_panel18.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel49.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Mayuresh  N.  Joshi");
        C001_panel18.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox19.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox19.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel18.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 38, 572, 30));

        C001_panel19.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("C019");
        C001_panel19.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel51.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Gaurav A. Deshpande");
        C001_panel19.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox20.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox20.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel19.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 68, 572, 30));

        C001_panel20.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("C020");
        C001_panel20.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel53.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Akash J. Gadhave");
        C001_panel20.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox21.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox21.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel20.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 98, 572, 30));

        C001_panel21.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("C021");
        C001_panel21.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel55.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Akash J. Gadhave");
        C001_panel21.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox22.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox22.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel21.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 128, 572, 30));

        C001_panel22.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("C022");
        C001_panel22.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel57.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Akash J. Gadhave");
        C001_panel22.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox23.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox23.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel22.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 158, 572, 30));

        C001_panel23.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("C023");
        C001_panel23.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel59.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Akash J. Gadhave");
        C001_panel23.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox24.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox24.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel23.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 188, 572, 30));

        C001_panel24.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("C024");
        C001_panel24.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel61.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Akash J. Gadhave");
        C001_panel24.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox25.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox25.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel24.add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 218, 572, 30));

        C001_panel25.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("C025");
        C001_panel25.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel63.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Akash J. Gadhave");
        C001_panel25.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox26.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox26.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel25.add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 248, 572, 30));

        C001_panel26.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel64.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("C026");
        C001_panel26.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel65.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Akash J. Gadhave");
        C001_panel26.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox27.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox27.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel26.add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 278, 572, 30));

        C001_panel27.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("C027");
        C001_panel27.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel67.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Akash J. Gadhave");
        C001_panel27.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox28.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox28.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel27.add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 308, 572, 30));

        C001_panel28.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("C028");
        C001_panel28.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel69.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("Akash J. Gadhave");
        C001_panel28.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox29.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox29.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel28.add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 338, 572, 30));

        C001_panel29.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("C029");
        C001_panel29.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel71.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Akash J. Gadhave");
        C001_panel29.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox30.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox30.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel29.add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 368, 572, 30));

        C001_panel30.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel72.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("C030");
        C001_panel30.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel73.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Akash J. Gadhave");
        C001_panel30.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox31.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox31.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel30.add(jCheckBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 398, 572, 30));

        C001_panel31.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("C031");
        C001_panel31.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel75.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("Akash J. Gadhave");
        C001_panel31.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox32.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox32.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel31.add(jCheckBox32, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 428, 572, 30));

        C001_panel32.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel76.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("C032");
        C001_panel32.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel77.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel77.setText("Akash J. Gadhave");
        C001_panel32.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox33.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox33.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel32.add(jCheckBox33, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 458, 572, 30));

        C001_panel33.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel78.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("C033");
        C001_panel33.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel79.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("Akash J. Gadhave");
        C001_panel33.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        jCheckBox34.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox34.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        C001_panel33.add(jCheckBox34, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        attendance_Panel_left2.add(C001_panel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 488, 572, 30));

        attendance_Panel_left1.add(attendance_Panel_left2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 575, 560));

        add(attendance_Panel_left1, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 40, 575, 560));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jButton1.setText("Submit");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel C001_panel;
    private javax.swing.JPanel C001_panel1;
    private javax.swing.JPanel C001_panel10;
    private javax.swing.JPanel C001_panel11;
    private javax.swing.JPanel C001_panel12;
    private javax.swing.JPanel C001_panel13;
    private javax.swing.JPanel C001_panel14;
    private javax.swing.JPanel C001_panel15;
    private javax.swing.JPanel C001_panel16;
    private javax.swing.JPanel C001_panel17;
    private javax.swing.JPanel C001_panel18;
    private javax.swing.JPanel C001_panel19;
    private javax.swing.JPanel C001_panel2;
    private javax.swing.JPanel C001_panel20;
    private javax.swing.JPanel C001_panel21;
    private javax.swing.JPanel C001_panel22;
    private javax.swing.JPanel C001_panel23;
    private javax.swing.JPanel C001_panel24;
    private javax.swing.JPanel C001_panel25;
    private javax.swing.JPanel C001_panel26;
    private javax.swing.JPanel C001_panel27;
    private javax.swing.JPanel C001_panel28;
    private javax.swing.JPanel C001_panel29;
    private javax.swing.JPanel C001_panel3;
    private javax.swing.JPanel C001_panel30;
    private javax.swing.JPanel C001_panel31;
    private javax.swing.JPanel C001_panel32;
    private javax.swing.JPanel C001_panel33;
    private javax.swing.JPanel C001_panel4;
    private javax.swing.JPanel C001_panel5;
    private javax.swing.JPanel C001_panel6;
    private javax.swing.JPanel C001_panel7;
    private javax.swing.JPanel C001_panel8;
    private javax.swing.JPanel C001_panel9;
    private javax.swing.JPanel attendance_Panel_left;
    private javax.swing.JPanel attendance_Panel_left1;
    private javax.swing.JPanel attendance_Panel_left2;
    private javax.swing.JLabel date_Label;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mark_Label;
    private javax.swing.JLabel mark_Label1;
    // End of variables declaration//GEN-END:variables
}
