/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import databaseConnectivity.MyPrisonConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Aakash
 */
public class mark_attendance_loadpanel extends javax.swing.JPanel {

    /**
     * Creates new form mark_attendance_loadpanel
     */
    Connection con;
    Mark_Attendance mark;
    public mark_attendance_loadpanel(Mark_Attendance ref) {
        initComponents();
        MyPrisonConnection o = new MyPrisonConnection();
                con = o.getMyConnection();
                mark = ref;
                
        //mark.attendance_present_vector.removeElement(fetch_id_label.getText());
        
    }

    public void setAbsentFlag(){
        mark.attendance_absent_vector.add(fetch_id_label.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        C001_panel1 = new javax.swing.JPanel();
        fetch_id_label = new javax.swing.JLabel();
        fetch_name_label = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(620, 30));
        setPreferredSize(new java.awt.Dimension(620, 30));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        C001_panel1.setBackground(new java.awt.Color(255, 255, 255));
        C001_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fetch_id_label.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        fetch_id_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C001_panel1.add(fetch_id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        fetch_name_label.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        fetch_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fetch_name_label.setText("Mayuresh  N.  Joshi");
        C001_panel1.add(fetch_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 360, 30));

        checkbox.setBackground(new java.awt.Color(255, 255, 255));
        checkbox.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        C001_panel1.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, 30));

        add(C001_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst;
        if(checkbox.isSelected())
        {
            mark.attendance_present_vector.add(fetch_id_label.getText());
            mark.attendance_absent_vector.removeElement(fetch_id_label.getText());
        }else{
            mark.attendance_present_vector.removeElement(fetch_id_label.getText());
            mark.attendance_absent_vector.add(fetch_id_label.getText());
        }
                
        
    }//GEN-LAST:event_checkboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel C001_panel1;
    public javax.swing.JCheckBox checkbox;
    public javax.swing.JLabel fetch_id_label;
    public javax.swing.JLabel fetch_name_label;
    // End of variables declaration//GEN-END:variables
}
