/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;
import java.awt.Color;

import databaseConnectivity.MyPrisonConnection;
import java.awt.BorderLayout;
//import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aakash
 */
public class prisoner_work_details extends javax.swing.JPanel {

    /**
     * Creates new form prisoner_work_details
     */
    Connection con;
    String c_id;
    public prisoner_work_details(String p_id) {
        initComponents();
         c_id = p_id;
        MyPrisonConnection o = new MyPrisonConnection();
        con = o.getMyConnection();
       //  initProgress(performance_load_panel1,80);
        //initProgress(attendance_load_panel1, 60);
        //initProgress(conduct_load_panel1, 40);
        
        
       // String unitname;
       
        
       
    }

    
      public void initProgress(javax.swing.JPanel objPanel,int max){
    
        
        ProgressPanel jpProgress = new ProgressPanel();
        objPanel.removeAll();
        objPanel.add(jpProgress,BorderLayout.CENTER);
        objPanel.revalidate();
        objPanel.repaint();
       drawProgress(jpProgress,max);
    }
   public void drawProgress(ProgressPanel objPanel ,int max){
     
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= max; i++) {
                    try {
                        objPanel.updateProgress(i);
                        objPanel.repaint();
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        System.out.println("Exception");
                    }
                    // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            }

        }).start();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        fetch_no_of_times_worked_label1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fetch_unit_name_label1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        conduct_load_panel1 = new javax.swing.JPanel();
        performance_load_panel1 = new javax.swing.JPanel();
        attendance_load_panel1 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1150, 2147483647));
        setMinimumSize(new java.awt.Dimension(1150, 160));
        setPreferredSize(new java.awt.Dimension(1150, 160));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("No Of Times Worked");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, -1));

        fetch_no_of_times_worked_label1.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        fetch_no_of_times_worked_label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_no_of_times_worked_label1.setText("3");
        jPanel3.add(fetch_no_of_times_worked_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Conduct");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        fetch_unit_name_label1.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        fetch_unit_name_label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_unit_name_label1.setText("Carpentry");
        jPanel3.add(fetch_unit_name_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Unit");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, -1));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Performance");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Attendance");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 10, -1, -1));

        conduct_load_panel1.setBackground(new java.awt.Color(255, 255, 255));
        conduct_load_panel1.setLayout(new java.awt.BorderLayout());
        jPanel3.add(conduct_load_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 120, 100));

        performance_load_panel1.setBackground(new java.awt.Color(255, 255, 255));
        performance_load_panel1.setLayout(new java.awt.BorderLayout());
        jPanel3.add(performance_load_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 120, 100));

        attendance_load_panel1.setBackground(new java.awt.Color(255, 255, 255));
        attendance_load_panel1.setLayout(new java.awt.BorderLayout());
        jPanel3.add(attendance_load_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 120, 100));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        //this.setBackground(new Color(240, 240, 240));
        
         
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
         //this.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel3MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel attendance_load_panel1;
    public javax.swing.JPanel conduct_load_panel1;
    public javax.swing.JLabel fetch_no_of_times_worked_label1;
    public javax.swing.JLabel fetch_unit_name_label1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel performance_load_panel1;
    // End of variables declaration//GEN-END:variables
}
