/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import databaseConnectivity.MyPrisonConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aakash
 */
public class schedule extends javax.swing.JPanel {

    /**
     * Creates new form schedule
     */
    Connection con = null;
    String current_head_id,description,start_time,end_time;
    public Vector selected_requirement_vector = new Vector(10,50);
    public Vector not_selected_requirement_vector = new Vector(10,50);
    
    
    
    public void setDetails(String hid,String p_id,String st,String et)
    {
        current_head_id=hid;
        description=p_id;
        start_time=st;
        end_time=et;
    }
    public schedule(String h_id,String p_id,String st_time,String end_tm) {
        initComponents();
        
         
             MyPrisonConnection o = new MyPrisonConnection();
             con = o.getMyConnection();
             
             current_head_id = h_id;
             description = p_id;
             start_time  = st_time;
             System.out.println(start_time);
             end_time = end_tm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fetch_id = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fetch_name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fetch_type = new javax.swing.JLabel();
        schedule_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        active_requirement_panel = new javax.swing.JPanel();
        panel_text = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel1.setText("Prisoner ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        fetch_id.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        fetch_id.setText("C001");
        jPanel1.add(fetch_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 60, -1));

        fetch_name.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        fetch_name.setText("Mayuresh N. Joshi");
        jPanel1.add(fetch_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 460, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel6.setText("Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, 20));

        fetch_type.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        fetch_type.setText("Rigorous");
        jPanel1.add(fetch_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 40));

        schedule_btn.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        schedule_btn.setText("SCHEDULE");
        schedule_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedule_btnActionPerformed(evt);
            }
        });
        add(schedule_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schedule To", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        active_requirement_panel.setBackground(new java.awt.Color(255, 255, 255));
        active_requirement_panel.setLayout(new javax.swing.BoxLayout(active_requirement_panel, javax.swing.BoxLayout.Y_AXIS));

        panel_text.setBackground(new java.awt.Color(255, 255, 255));
        panel_text.setMaximumSize(new java.awt.Dimension(0, 0));
        panel_text.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        active_requirement_panel.add(panel_text);

        jScrollPane2.setViewportView(active_requirement_panel);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, 730, 240));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel7.setText("Ends On");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 740, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void schedule_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedule_btnActionPerformed
        // TODO add your handling code here:
         PreparedStatement pst;
        ResultSet res;
        int size;
           
                
         size = selected_requirement_vector.size();
        
        for(int i=0;i<size;i++)
        {
        
        try {
            String selected_req = (String) selected_requirement_vector.elementAt(i);
            String qu = "INSERT INTO schedule VALUES(?,?,?,?)";
            pst = con.prepareStatement(qu);
            System.out.println("start time : "+start_time);
          // head = new head_dash(current_head_id);
          String con_time=selected_requirement_vector.elementAt(i).toString();
            System.out.println(selected_requirement_vector.elementAt(i).toString());
            int sep_index=con_time.indexOf("$");
            start_time=con_time.substring(0,sep_index);
            end_time=con_time.substring(sep_index+1, con_time.length());
            System.out.println(start_time);
            System.out.println(end_time);
               pst.setString(1, description);
            pst.setString(2, current_head_id);
            pst.setString(3, start_time);
            pst.setString(4, end_time);
            
                
       
                
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Scheduled Successfully..!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ""+ex.getMessage());
            Logger.getLogger(Mark_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
           
        /*size = not_selected_requirement_vector.size();
        System.out.println(size);
        for(int i=0;i<size;i++)
        {
        
        try {
            System.out.println(size);
            String selected_req = (String) not_selected_requirement_vector.elementAt(i);
            String qu = "INSERT INTO schedule VALUES(?,?,?,?)";
            pst = con.prepareStatement(qu);
            
          // head = new head_dash(current_head_id);
         
               pst.setString(1, selected_req);
            pst.setString(2, current_head_id);
                 pst.setString(1, description);
            pst.setString(2, current_head_id);
            pst.setString(3, start_time);
            pst.setString(4, end_time);
               
                
            int j = pst.executeUpdate();
            if(i>0){
                    JOptionPane.showMessageDialog(null, "Attendance successfully Marked");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Error in marking attendance");
                }
        } catch (SQLException ex) {
            Logger.getLogger(Mark_Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
    }//GEN-LAST:event_schedule_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel active_requirement_panel;
    public javax.swing.JLabel fetch_id;
    public javax.swing.JLabel fetch_name;
    public javax.swing.JLabel fetch_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_text;
    public javax.swing.JButton schedule_btn;
    // End of variables declaration//GEN-END:variables
}
