/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import databaseConnectivity.MyPrisonConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aakash Gadhave
 */
public class slot_panel extends javax.swing.JPanel {

    /**
     * Creates new form slot_panel
     */
    Connection con;
    String unit_code;
    String duration;
    private add_Requirement add_req;
    public slot_panel(String u_code,String dur) {
        initComponents();
          MyPrisonConnection o = new MyPrisonConnection();
                con = o.getMyConnection();
                unit_code = u_code;
                duration = dur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fetch_endtime_label = new javax.swing.JLabel();
        fetch_start_time_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel5.setText("14:00");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Available Slot");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 0, -1, 30));

        fetch_endtime_label.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        add(fetch_endtime_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        fetch_start_time_label.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        add(fetch_start_time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel3.setText("to");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel fetch_endtime_label;
    public javax.swing.JLabel fetch_start_time_label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
