/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import javax.swing.JPanel;

/**
 *
 * @author Aakash
 */
public class superintendant_view_prison_history_panel extends javax.swing.JPanel {

    /**
     * Creates new form superintendant_view_prison_history_panel
     */
    JPanel view1;
    prisoner_work_details work;
    String prisoner_id,prisoner_name,prisoner_type,conviction_date;
    int days_to_release;
    public superintendant_view_prison_history_panel(JPanel view, String pid, String pname, String ptype,String convict_date,int days) {
        initComponents();
        view1 = view;
        prisoner_id=pid;
        prisoner_name=pname;
        prisoner_type=ptype;
        conviction_date = convict_date;
        days_to_release = days;
        
        
        
        fetch_id.setText(prisoner_id);
        fetch_name.setText(prisoner_name);
        fetch_type.setText(prisoner_type);
        fetch_convictiondate_label.setText(conviction_date);
        fetch_days_to_release_label.setText(""+days_to_release);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        horizontal_prisoner_details_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fetch_id = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fetch_name = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fetch_type = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fetch_days_to_release_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fetch_convictiondate_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loading_history_panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        horizontal_prisoner_details_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Prisoner ID");
        horizontal_prisoner_details_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        fetch_id.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        fetch_id.setText("C001");
        horizontal_prisoner_details_panel.add(fetch_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        horizontal_prisoner_details_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 60, -1));

        fetch_name.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        fetch_name.setText("Mayuresh N. Joshi");
        horizontal_prisoner_details_panel.add(fetch_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setText("Type");
        horizontal_prisoner_details_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        fetch_type.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        fetch_type.setText("Rigorous");
        horizontal_prisoner_details_panel.add(fetch_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 20));

        add(horizontal_prisoner_details_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 40));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 27)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Work History");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 150, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fetch_days_to_release_label.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        fetch_days_to_release_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_days_to_release_label.setText("390");
        jPanel1.add(fetch_days_to_release_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Days To Release");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, -1));

        fetch_convictiondate_label.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        fetch_convictiondate_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fetch_convictiondate_label.setText("11-12-2017");
        jPanel1.add(fetch_convictiondate_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Conviction Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 110));

        jScrollPane1.setHorizontalScrollBar(null);

        loading_history_panel.setBackground(new java.awt.Color(255, 255, 255));
        loading_history_panel.setLayout(new javax.swing.BoxLayout(loading_history_panel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(loading_history_panel);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1130, 540));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel fetch_convictiondate_label;
    public javax.swing.JLabel fetch_days_to_release_label;
    public javax.swing.JLabel fetch_id;
    public javax.swing.JLabel fetch_name;
    public javax.swing.JLabel fetch_type;
    private javax.swing.JPanel horizontal_prisoner_details_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel loading_history_panel;
    // End of variables declaration//GEN-END:variables
}
